import { ItemCard, Typography } from 'components/index';
import { FlatListComponent, RowComponent } from 'components/common';
import { COMMON_TEXT, IMAGES, SCREENS, SVG, TEMPORARY_TEXT } from 'constants/index';
import { SvgProps } from 'react-native-svg';
import { COLORS, STYLES } from 'utils/index';
import { FontSize, FontWeight } from 'types/index';
import { navigate } from 'navigation/index';
import { styles } from './styles';
import { FoodCard } from '../FoodCard';

export type CategoryType = {
  id: string;
  name: string;
  image: React.FC<SvgProps>;
};

export type ItemType = {
  id: string;
  name: string;
  image: string;
  address: string;
  city: string;
  country: string;
  distance?: string;
  isOpen?: boolean;
  openTime?: string;
  isLiked?: boolean;
  website?: string;
  latitude?: string;
  longitude?: string;
  telephone?: string;
  email?: string;
  description?: string;
  rating?: string;
  phoneNumber: string;
  category: string;
  totalRatings?: string;
  services?: { image: string; name: string; price: string }[];
  businessHours?: { day: string; start_time: string; end_time: string }[];
  rooms?: {
    id: string;
    name: string;
    image: string;
    icon: boolean;
    description: string;
    price: string;
  }[];
};

export type SubCategoryType = {
  id: string;
  key: string;
  subCategories: {
    id: string;
    key: string;
    image: string;
    items: ItemType[];
    categories?: { id: string; name: string; image: string }[];
  }[];
  items?: ItemType[];
};

export const categoriesList: CategoryType[] = [
  { id: '1', name: 'Life Style', image: SVG.LIFE_STYLE },
  { id: '2', name: 'Food', image: SVG.FOOD },
  { id: '3', name: 'Groceries', image: SVG.GROCERIES },
  { id: '4', name: 'Wears', image: SVG.WEARS },
  { id: '5', name: 'Health', image: SVG.HEALTH },
  { id: '6', name: 'Real State', image: SVG.REAL_STATE },
  { id: '7', name: 'Events', image: SVG.EVENTS },
  { id: '8', name: 'Others', image: SVG.OTHERS },
];

export const FavoritesList: ItemType[] = [
  {
    id: '1',
    name: 'Golden Sands Boutique Hotel',
    image: IMAGES.HOTELS,
    address: '123 Maplewood Lane Springfield',
    city: 'London',
    country: 'UK',
    website: 'www.goldensands.com',
    telephone: '(480) 000-0010',
    email: 'goldensands@gmail.com',
    phoneNumber: '1234567890',
    category: 'Life Style',
    distance: '4.5 Miles',
    latitude: '37.774929',
    longitude: '-122.419416',
    description: TEMPORARY_TEXT.LORUM_IPSUM,
    isOpen: true,
    openTime: '2 pm - 8 pm',
    isLiked: true,
  },
  {
    id: '2',
    name: 'Golden Boutique Hotel',
    image: IMAGES.HOTEL_1,
    address: '123 Maplewood Lane Springfield',
    city: 'London',
    category: 'Life Style',
    country: 'UK',
    website: 'www.goldensandsboutiquehotel.com',
    telephone: '(480) 000-0010',
    email: 'goldensands@gmail.com',
    phoneNumber: '1234567890',
    distance: '4.5 Miles',
    isOpen: true,
    openTime: '2 pm - 8 pm',
    latitude: '37.774929',
    longitude: '-122.419416',
    description: TEMPORARY_TEXT.LORUM_IPSUM,
    isLiked: true,
  },
  {
    id: '3',
    name: 'Saloon',
    image: IMAGES.SALOONS,
    address: '123 Maplewood Lane Springfield',
    city: 'London',
    country: 'UK',
    category: 'Life Style',
    website: 'www.walmart.com',
    telephone: '(480) 000-0010',
    email: 'walmart@gmail.com',
    phoneNumber: '1234567890',
    distance: '4.5 Miles',
    latitude: '37.774929',
    longitude: '-122.419416',
    description: TEMPORARY_TEXT.LORUM_IPSUM,
    isOpen: true,
    openTime: '2 pm - 8 pm',
    isLiked: true,
    services: [
      { image: IMAGES.SALOONS, name: 'Head Massage', price: '10' },
      { image: IMAGES.SALOON_1, name: 'Head Massage', price: '20' },
      { image: IMAGES.SALOON_2, name: 'Head Massage', price: '30' },
      { image: IMAGES.SALOONS, name: 'Head Massage', price: '30' },
      { image: IMAGES.SALOON_1, name: 'Head Massage', price: '30' },
      { image: IMAGES.SALOON_2, name: 'Head Massage', price: '30' },
    ],
  },
  {
    id: '4',
    name: 'Peace Pharmacy',
    latitude: '37.774929',
    longitude: '-122.419416',
    description: TEMPORARY_TEXT.LORUM_IPSUM,
    image: IMAGES.PEACE_PHARMACY,
    address: '123 Maplewood Lane Springfield',
    city: 'London',
    country: 'UK',
    category: 'Pharmacy',
    website: 'www.peacepharmacy.com',
    telephone: '(480) 000-0010',
    email: 'peacepharmacy@gmail.com',
    phoneNumber: '1234567890',
    distance: '4.5 Miles',
    isOpen: true,
    openTime: '2 pm - 8 pm',
    isLiked: true,
  },
  {
    id: '5',
    name: 'Walmart',
    image: IMAGES.WALMART,
    address: '123 Maplewood Lane Springfield',
    city: 'London',
    country: 'UK',
    latitude: '37.774929',
    longitude: '-122.419416',
    description: TEMPORARY_TEXT.LORUM_IPSUM,
    website: 'www.walmart.com',
    telephone: '(480) 000-0010',
    email: 'walmart@gmail.com',
    phoneNumber: '1234567890',
    distance: '4.5 Miles',
    category: 'Life Style',
    isOpen: true,
    openTime: '2 pm - 8 pm',
    isLiked: true,
  },
  {
    id: '6',
    name: 'Saloon 6',
    image: IMAGES.SALOONS,
    address: '123 Maplewood Lane Springfield',
    city: 'London',
    country: 'UK',
    website: 'www.saloon.com',
    telephone: '(480) 000-0010',
    email: 'saloon@gmail.com',
    phoneNumber: '1234567890',
    distance: '4.5 Miles',
    category: 'Wears',
    latitude: '37.774929',
    longitude: '-122.419416',
    description: TEMPORARY_TEXT.LORUM_IPSUM,
    isOpen: true,
    openTime: '2 pm - 8 pm',
    isLiked: true,
    services: [
      { image: IMAGES.SALOONS, name: 'Head Massage', price: '10' },
      { image: IMAGES.SALOON_1, name: 'Head Massage', price: '20' },
      { image: IMAGES.SALOON_2, name: 'Head Massage', price: '30' },
      { image: IMAGES.SALOONS, name: 'Head Massage', price: '30' },
      { image: IMAGES.SALOON_1, name: 'Head Massage', price: '30' },
      { image: IMAGES.SALOON_2, name: 'Head Massage', price: '30' },
    ],
  },
];

export const subCategoriesList: SubCategoryType[] = [
  {
    id: '1',
    key: 'Life Style',
    subCategories: [
      {
        id: '1',
        key: 'Hotels',
        image: IMAGES.HOTELS,
        items: [
          {
            id: '1',
            name: 'Golden Sands Boutique Hotel',
            image: IMAGES.HOTEL_1,
            website: 'www.hotel.com',
            email: 'hotel@gmail.com',
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            telephone: '(480) 000-0010',
            phoneNumber: '1234567890',
            category: 'Hotels',
            distance: '4.5 Miles',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
            rooms: [
              {
                id: '1',
                name: 'Deluxe Single Room',
                icon: true,
                description: '1 Twin Bed',
                image: IMAGES.HOTELS,
                price: '100',
              },
              {
                id: '2',
                name: 'Deluxe Twin Room',
                icon: true,
                description: '2 Twin Bed',
                image: IMAGES.HOTEL_2,
                price: '100',
              },
              {
                id: '3',
                name: 'Deluxe Single Room',
                icon: true,
                description: '1 Twin Bed',
                image: IMAGES.HOTEL_1,
                price: '100',
              },
              {
                id: '4',
                name: 'Deluxe Twin Room',
                icon: true,
                description: '2 Twin Bed',
                image: IMAGES.HOTELS,
                price: '100',
              },
              {
                id: '5',
                name: 'Deluxe Single Room',
                icon: true,
                description: '1 Twin Bed',
                image: IMAGES.HOTEL_2,
                price: '100',
              },
              {
                id: '6',
                name: 'Deluxe Twin Room',
                icon: true,
                description: '2 Twin Bed',
                image: IMAGES.HOTEL_1,
                price: '100',
              },
            ],
          },
          {
            id: '2',
            name: 'Golden Sands Boutique Hotel',
            image: IMAGES.HOTEL_2,
            website: 'www.hotel.com',
            email: 'hotel@gmail.com',
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            category: 'Hotels',
            country: 'UK',
            telephone: '(480) 000-0010',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            isOpen: true,
            openTime: '2 pm - 8 pm',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            isLiked: false,
            rooms: [
              {
                id: '1',
                name: 'Deluxe Single Room',
                icon: true,
                description: '1 Twin Bed',
                image: IMAGES.HOTELS,
                price: '100',
              },
              {
                id: '2',
                name: 'Deluxe Twin Room',
                icon: true,
                description: '2 Twin Bed',
                image: IMAGES.HOTEL_2,
                price: '100',
              },
              {
                id: '3',
                name: 'Deluxe Single Room',
                icon: true,
                description: '1 Twin Bed',
                image: IMAGES.HOTEL_1,
                price: '100',
              },
              {
                id: '4',
                name: 'Deluxe Twin Room',
                icon: true,
                description: '2 Twin Bed',
                image: IMAGES.HOTELS,
                price: '100',
              },
              {
                id: '5',
                name: 'Deluxe Single Room',
                icon: true,
                description: '1 Twin Bed',
                image: IMAGES.HOTEL_2,
                price: '100',
              },
              {
                id: '6',
                name: 'Deluxe Twin Room',
                icon: true,
                description: '2 Twin Bed',
                image: IMAGES.HOTEL_1,
                price: '100',
              },
            ],
          },
          {
            id: '3',
            name: 'Golden Sands Boutique Hotel',
            image: IMAGES.HOTEL_1,
            website: 'www.hotel.com',
            email: 'hotel@gmail.com',
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            category: 'Hotels',
            telephone: '(480) 000-0010',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
            rooms: [
              {
                id: '1',
                name: 'Deluxe Single Room',
                icon: true,
                description: '1 Twin Bed',
                image: IMAGES.HOTELS,
                price: '100',
              },
              {
                id: '2',
                name: 'Deluxe Twin Room',
                icon: true,
                description: '2 Twin Bed',
                image: IMAGES.HOTEL_2,
                price: '100',
              },
              {
                id: '3',
                name: 'Deluxe Single Room',
                icon: true,
                description: '1 Twin Bed',
                image: IMAGES.HOTEL_1,
                price: '100',
              },
              {
                id: '4',
                name: 'Deluxe Twin Room',
                icon: true,
                description: '2 Twin Bed',
                image: IMAGES.HOTELS,
                price: '100',
              },
              {
                id: '5',
                name: 'Deluxe Single Room',
                icon: true,
                description: '1 Twin Bed',
                image: IMAGES.HOTEL_2,
                price: '100',
              },
              {
                id: '6',
                name: 'Deluxe Twin Room',
                icon: true,
                description: '2 Twin Bed',
                image: IMAGES.HOTEL_1,
                price: '100',
              },
            ],
          },
          {
            id: '4',
            name: 'Golden Sands Boutique Hotel',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            image: IMAGES.HOTEL_2,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            category: 'Hotels',
            website: 'www.hotel.com',
            telephone: '(480) 000-0010',
            email: 'hotel@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
            rooms: [
              {
                id: '1',
                name: 'Deluxe Single Room',
                icon: true,
                description: '1 Twin Bed',
                image: IMAGES.HOTELS,
                price: '100',
              },
              {
                id: '2',
                name: 'Deluxe Twin Room',
                icon: true,
                description: '2 Twin Bed',
                image: IMAGES.HOTEL_2,
                price: '100',
              },
              {
                id: '3',
                name: 'Deluxe Single Room',
                icon: true,
                description: '1 Twin Bed',
                image: IMAGES.HOTEL_1,
                price: '100',
              },
              {
                id: '4',
                name: 'Deluxe Twin Room',
                icon: true,
                description: '2 Twin Bed',
                image: IMAGES.HOTELS,
                price: '100',
              },
              {
                id: '5',
                name: 'Deluxe Single Room',
                icon: true,
                description: '1 Twin Bed',
                image: IMAGES.HOTEL_2,
                price: '100',
              },
              {
                id: '6',
                name: 'Deluxe Twin Room',
                icon: true,
                description: '2 Twin Bed',
                image: IMAGES.HOTEL_1,
                price: '100',
              },
            ],
          },
          {
            id: '5',
            name: 'Golden Sands Boutique Hotel',
            image: IMAGES.HOTEL_2,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            website: 'www.hotel.com',
            telephone: '(480) 000-0010',
            email: 'hotel@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            category: 'Hotels',
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
            rooms: [
              {
                id: '1',
                name: 'Deluxe Single Room',
                icon: true,
                description: '1 Twin Bed',
                image: IMAGES.HOTELS,
                price: '100',
              },
              {
                id: '2',
                name: 'Deluxe Twin Room',
                icon: true,
                description: '2 Twin Bed',
                image: IMAGES.HOTEL_2,
                price: '100',
              },
              {
                id: '3',
                name: 'Deluxe Single Room',
                icon: true,
                description: '1 Twin Bed',
                image: IMAGES.HOTEL_1,
                price: '100',
              },
              {
                id: '4',
                name: 'Deluxe Twin Room',
                icon: true,
                description: '2 Twin Bed',
                image: IMAGES.HOTELS,
                price: '100',
              },
              {
                id: '5',
                name: 'Deluxe Single Room',
                icon: true,
                description: '1 Twin Bed',
                image: IMAGES.HOTEL_2,
                price: '100',
              },
              {
                id: '6',
                name: 'Deluxe Twin Room',
                icon: true,
                description: '2 Twin Bed',
                image: IMAGES.HOTEL_1,
                price: '100',
              },
            ],
          },
          {
            id: '6',
            name: 'Golden Sands Boutique Hotel',
            image: IMAGES.HOTEL_1,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            website: 'www.hotel.com',
            telephone: '(480) 000-0010',
            email: 'hotel@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            category: 'Hotels',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
            rooms: [
              {
                id: '1',
                name: 'Deluxe Single Room',
                icon: true,
                description: '1 Twin Bed',
                image: IMAGES.HOTELS,
                price: '100',
              },
              {
                id: '2',
                name: 'Deluxe Twin Room',
                icon: true,
                description: '2 Twin Bed',
                image: IMAGES.HOTEL_2,
                price: '100',
              },
              {
                id: '3',
                name: 'Deluxe Single Room',
                icon: true,
                description: '1 Twin Bed',
                image: IMAGES.HOTEL_1,
                price: '100',
              },
              {
                id: '4',
                name: 'Deluxe Twin Room',
                icon: true,
                description: '2 Twin Bed',
                image: IMAGES.HOTELS,
                price: '100',
              },
              {
                id: '5',
                name: 'Deluxe Single Room',
                icon: true,
                description: '1 Twin Bed',
                image: IMAGES.HOTEL_2,
                price: '100',
              },
              {
                id: '6',
                name: 'Deluxe Twin Room',
                icon: true,
                description: '2 Twin Bed',
                image: IMAGES.HOTEL_1,
                price: '100',
              },
            ],
          },
        ],
      },
      {
        id: '2',
        key: 'SPA',
        image: IMAGES.SPA,

        items: [
          {
            id: '1',
            name: 'Sundara In & Spa',
            image: IMAGES.SPA,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            website: 'www.spa.com',
            telephone: '(480) 000-0010',
            email: 'spa@gmail.com',
            phoneNumber: '1234567890',
            category: 'SPA',
            distance: '4.5 Miles',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
            services: [
              { image: IMAGES.SPA, name: 'Aesthetician 1', price: '10' },
              { image: IMAGES.SPA, name: 'Aesthetician 2', price: '20' },
              { image: IMAGES.SPA, name: 'Aesthetician 3', price: '30' },
              { image: IMAGES.SPA, name: 'Aesthetician 4', price: '30' },
              { image: IMAGES.SPA, name: 'Aesthetician 5', price: '30' },
              { image: IMAGES.SPA, name: 'Aesthetician 6', price: '30' },
            ],
            businessHours: [
              { day: 'Monday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Tuesday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Wednesday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Thursday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Friday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Saturday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Sunday', start_time: '9:00 AM', end_time: '5:00 PM' },
            ],
          },
          {
            id: '2',
            name: 'Sundara In & Spa',
            image: IMAGES.SPA,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            category: 'SPA',
            country: 'UK',
            website: 'www.spa.com',
            telephone: '(480) 000-0010',
            email: 'spa@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            isOpen: true,
            openTime: '2 pm - 8 pm',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            isLiked: false,
            services: [
              { image: IMAGES.SPA, name: 'Aesthetician 1', price: '10' },
              { image: IMAGES.SPA, name: 'Aesthetician 2', price: '20' },
              { image: IMAGES.SPA, name: 'Aesthetician 3', price: '30' },
              { image: IMAGES.SPA, name: 'Aesthetician 4', price: '30' },
              { image: IMAGES.SPA, name: 'Aesthetician 5', price: '30' },
              { image: IMAGES.SPA, name: 'Aesthetician 6', price: '30' },
            ],
            businessHours: [
              { day: 'Monday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Tuesday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Wednesday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Thursday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Friday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Saturday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Sunday', start_time: '9:00 AM', end_time: '5:00 PM' },
            ],
          },
          {
            id: '3',
            name: 'Sundara In & Spa',
            image: IMAGES.SPA,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            category: 'SPA',
            website: 'www.spa.com',
            telephone: '(480) 000-0010',
            email: 'spa@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
            services: [
              { image: IMAGES.SPA, name: 'Aesthetician 1', price: '10' },
              { image: IMAGES.SPA, name: 'Aesthetician 2', price: '20' },
              { image: IMAGES.SPA, name: 'Aesthetician 3', price: '30' },
              { image: IMAGES.SPA, name: 'Aesthetician 4', price: '30' },
              { image: IMAGES.SPA, name: 'Aesthetician 5', price: '30' },
              { image: IMAGES.SPA, name: 'Aesthetician 6', price: '30' },
            ],
            businessHours: [
              { day: 'Monday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Tuesday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Wednesday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Thursday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Friday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Saturday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Sunday', start_time: '9:00 AM', end_time: '5:00 PM' },
            ],
          },
          {
            id: '4',
            name: 'Sundara In & Spa',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            image: IMAGES.SPA,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            category: 'SPA',
            website: 'www.spa.com',
            telephone: '(480) 000-0010',
            email: 'spa@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
            services: [
              { image: IMAGES.SPA, name: 'Aesthetician 1', price: '10' },
              { image: IMAGES.SPA, name: 'Aesthetician 2', price: '20' },
              { image: IMAGES.SPA, name: 'Aesthetician 3', price: '30' },
              { image: IMAGES.SPA, name: 'Aesthetician 4', price: '30' },
              { image: IMAGES.SPA, name: 'Aesthetician 5', price: '30' },
              { image: IMAGES.SPA, name: 'Aesthetician 6', price: '30' },
            ],
            businessHours: [
              { day: 'Monday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Tuesday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Wednesday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Thursday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Friday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Saturday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Sunday', start_time: '9:00 AM', end_time: '5:00 PM' },
            ],
          },
          {
            id: '5',
            name: 'Sundara In & Spa',
            image: IMAGES.SPA,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            website: 'www.spa.com',
            email: 'spa@gmail.com',
            telephone: '(480) 000-0010',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            category: 'SPA',
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
            services: [
              { image: IMAGES.SPA, name: 'Aesthetician 1', price: '10' },
              { image: IMAGES.SPA, name: 'Aesthetician 2', price: '20' },
              { image: IMAGES.SPA, name: 'Aesthetician 3', price: '30' },
              { image: IMAGES.SPA, name: 'Aesthetician 4', price: '30' },
              { image: IMAGES.SPA, name: 'Aesthetician 5', price: '30' },
              { image: IMAGES.SPA, name: 'Aesthetician 6', price: '30' },
            ],
            businessHours: [
              { day: 'Monday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Tuesday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Wednesday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Thursday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Friday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Saturday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Sunday', start_time: '9:00 AM', end_time: '5:00 PM' },
            ],
          },
          {
            id: '6',
            name: 'Sundara In & Spa',
            image: IMAGES.SPA,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            website: 'www.spa.com',
            telephone: '(480) 000-0010',
            email: 'spa@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            category: 'SPA',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
            services: [
              { image: IMAGES.SPA, name: 'Aesthetician 1', price: '10' },
              { image: IMAGES.SPA, name: 'Aesthetician 2', price: '20' },
              { image: IMAGES.SPA, name: 'Aesthetician 3', price: '30' },
              { image: IMAGES.SPA, name: 'Aesthetician 4', price: '30' },
              { image: IMAGES.SPA, name: 'Aesthetician 5', price: '30' },
              { image: IMAGES.SPA, name: 'Aesthetician 6', price: '30' },
            ],
            businessHours: [
              { day: 'Monday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Tuesday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Wednesday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Thursday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Friday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Saturday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Sunday', start_time: '9:00 AM', end_time: '5:00 PM' },
            ],
          },
        ],
      },
      {
        id: '3',
        key: 'Saloons',
        image: IMAGES.SALOONS,

        items: [
          {
            id: '1',
            name: 'Salon 1',
            image: IMAGES.SALOON_1,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            website: 'www.salon.com',
            telephone: '(480) 000-0010',
            email: 'salon@gmail.com',
            phoneNumber: '1234567890',
            category: 'Saloons',
            distance: '4.5 Miles',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
            services: [
              { image: IMAGES.SALOONS, name: 'Head Massage', price: '10' },
              { image: IMAGES.SALOON_1, name: 'Head Massage', price: '20' },
              { image: IMAGES.SALOON_2, name: 'Head Massage', price: '30' },
              { image: IMAGES.SALOONS, name: 'Head Massage', price: '30' },
              { image: IMAGES.SALOON_1, name: 'Head Massage', price: '30' },
              { image: IMAGES.SALOON_2, name: 'Head Massage', price: '30' },
            ],
            businessHours: [
              { day: 'Monday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Tuesday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Wednesday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Thursday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Friday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Saturday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Sunday', start_time: '9:00 AM', end_time: '5:00 PM' },
            ],
          },
          {
            id: '2',
            name: 'Salon 2',
            image: IMAGES.SALOON_2,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            category: 'Saloons',
            country: 'UK',
            website: 'www.salon.com',
            telephone: '(480) 000-0010',
            email: 'salon@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            isOpen: true,
            openTime: '2 pm - 8 pm',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            isLiked: false,
            services: [
              { image: IMAGES.SALOONS, name: 'Head Massage', price: '10' },
              { image: IMAGES.SALOON_1, name: 'Head Massage', price: '20' },
              { image: IMAGES.SALOON_2, name: 'Head Massage', price: '30' },
              { image: IMAGES.SALOONS, name: 'Head Massage', price: '30' },
              { image: IMAGES.SALOON_1, name: 'Head Massage', price: '30' },
              { image: IMAGES.SALOON_2, name: 'Head Massage', price: '30' },
            ],
            businessHours: [
              { day: 'Monday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Tuesday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Wednesday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Thursday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Friday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Saturday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Sunday', start_time: '9:00 AM', end_time: '5:00 PM' },
            ],
          },
          {
            id: '3',
            name: 'Salon 3',
            image: IMAGES.SALOON_1,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            category: 'Saloons',
            website: 'www.salon.com',
            telephone: '(480) 000-0010',
            email: 'salon@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
            services: [
              { image: IMAGES.SALOONS, name: 'Head Massage', price: '10' },
              { image: IMAGES.SALOON_1, name: 'Head Massage', price: '20' },
              { image: IMAGES.SALOON_2, name: 'Head Massage', price: '30' },
              { image: IMAGES.SALOONS, name: 'Head Massage', price: '30' },
              { image: IMAGES.SALOON_1, name: 'Head Massage', price: '30' },
              { image: IMAGES.SALOON_2, name: 'Head Massage', price: '30' },
            ],
            businessHours: [
              { day: 'Monday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Tuesday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Wednesday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Thursday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Friday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Saturday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Sunday', start_time: '9:00 AM', end_time: '5:00 PM' },
            ],
          },
          {
            id: '4',
            name: 'Salon 4',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            image: IMAGES.SALOON_2,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            category: 'Saloons',
            website: 'www.salon.com',
            telephone: '(480) 000-0010',
            email: 'salon@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
            services: [
              { image: IMAGES.SALOONS, name: 'Head Massage', price: '10' },
              { image: IMAGES.SALOON_1, name: 'Head Massage', price: '20' },
              { image: IMAGES.SALOON_2, name: 'Head Massage', price: '30' },
              { image: IMAGES.SALOONS, name: 'Head Massage', price: '30' },
              { image: IMAGES.SALOON_1, name: 'Head Massage', price: '30' },
              { image: IMAGES.SALOON_2, name: 'Head Massage', price: '30' },
            ],
            businessHours: [
              { day: 'Monday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Tuesday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Wednesday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Thursday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Friday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Saturday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Sunday', start_time: '9:00 AM', end_time: '5:00 PM' },
            ],
          },
          {
            id: '5',
            name: 'Salon 5',
            image: IMAGES.SALOON_1,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            latitude: '37.774929',
            category: 'Saloons',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            website: 'www.salon.com',
            telephone: '(480) 000-0010',
            email: 'salon@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',

            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
            services: [
              { image: IMAGES.SALOONS, name: 'Head Massage', price: '10' },
              { image: IMAGES.SALOON_1, name: 'Head Massage', price: '20' },
              { image: IMAGES.SALOON_2, name: 'Head Massage', price: '30' },
              { image: IMAGES.SALOONS, name: 'Head Massage', price: '30' },
              { image: IMAGES.SALOON_1, name: 'Head Massage', price: '30' },
              { image: IMAGES.SALOON_2, name: 'Head Massage', price: '30' },
            ],
            businessHours: [
              { day: 'Monday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Tuesday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Wednesday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Thursday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Friday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Saturday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Sunday', start_time: '9:00 AM', end_time: '5:00 PM' },
            ],
          },
          {
            id: '6',
            name: 'Salon 6',
            image: IMAGES.SALOON_2,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            website: 'www.salon.com',
            telephone: '(480) 000-0010',
            email: 'salon@gmail.com',
            category: 'Saloons',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',

            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
            services: [
              { image: IMAGES.SALOONS, name: 'Head Massage', price: '10' },
              { image: IMAGES.SALOON_1, name: 'Head Massage', price: '20' },
              { image: IMAGES.SALOON_2, name: 'Head Massage', price: '30' },
              { image: IMAGES.SALOONS, name: 'Head Massage', price: '30' },
              { image: IMAGES.SALOON_1, name: 'Head Massage', price: '30' },
              { image: IMAGES.SALOON_2, name: 'Head Massage', price: '30' },
            ],
            businessHours: [
              { day: 'Monday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Tuesday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Wednesday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Thursday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Friday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Saturday', start_time: '9:00 AM', end_time: '5:00 PM' },
              { day: 'Sunday', start_time: '9:00 AM', end_time: '5:00 PM' },
            ],
          },
        ],
      },
    ],
  },
  {
    id: '2',
    key: 'Food',
    subCategories: [
      {
        id: '1',
        key: 'Order Your Food',
        image: IMAGES.ORDER_FOOD,
        categories: [
          {
            id: '1',
            name: 'BBQ',
            image: IMAGES.CATEGORY_2_BBQ,
          },
          {
            id: '2',
            name: 'Afang Soup',
            image: IMAGES.CATEGORY_1,
          },
          {
            id: '3',
            name: 'BBQ',
            image: IMAGES.CATEGORY_2_BBQ,
          },
          {
            id: '4',
            name: 'Afang Soup',
            image: IMAGES.CATEGORY_1,
          },
          {
            id: '5',
            name: 'BBQ',
            image: IMAGES.CATEGORY_2_BBQ,
          },
        ],
        items: [
          {
            id: '1',
            name: 'Starbucks',
            image: IMAGES.STARBUCKS,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            website: 'www.starbucks.com',
            telephone: '(480) 000-0010',
            email: 'starbucks@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            isOpen: true,
            category: 'Order Your Food',
            openTime: '2 pm - 8 pm',
            isLiked: false,
          },
          {
            id: '2',
            name: "McDonald's",
            image: IMAGES.MACDONALDS,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            website: 'www.mcdonalds.com',
            telephone: '(480) 000-0010',
            email: 'mcdonalds@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            category: 'Order Your Food',
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
          },
          {
            id: '3',
            name: 'Starbucks',
            image: IMAGES.STARBUCKS,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            category: 'Order Your Food',
            country: 'UK',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            website: 'www.starbucks.com',
            telephone: '(480) 000-0010',
            email: 'starbucks@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
          },
          {
            id: '4',
            name: "McDonald's",
            image: IMAGES.MACDONALDS,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            website: 'www.mcdonalds.com',
            telephone: '(480) 000-0010',
            email: 'mcdonalds@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            category: 'Order Your Food',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
          },

          {
            id: '5',
            name: 'Starbucks',
            image: IMAGES.STARBUCKS,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            website: 'www.starbucks.com',
            telephone: '(480) 000-0010',
            email: 'starbucks@gmail.com',
            phoneNumber: '1234567890',
            country: 'UK',
            category: 'Order Your Food',
            distance: '4.5 Miles',
            isOpen: true,
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            openTime: '2 pm - 8 pm',
            isLiked: false,
          },
          {
            id: '6',
            name: "McDonald's",
            image: IMAGES.MACDONALDS,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            website: 'www.mcdonalds.com',
            telephone: '(480) 000-0010',
            latitude: '37.774929',
            longitude: '-122.419416',
            email: 'mcdonalds@gmail.com',
            phoneNumber: '1234567890',
            category: 'Order Your Food',
            country: 'UK',
            distance: '4.5 Miles',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
          },
        ],
      },
      {
        id: '2',
        key: 'Restaurant Reservation',
        image: IMAGES.RESTAURANT_RESERVATION,
        items: [
          {
            id: '1',
            name: 'Walmart 1',
            image: IMAGES.WALMART,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            website: 'www.walmart.com',
            telephone: '(480) 000-0010',
            email: 'walmart@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            isOpen: true,
            category: 'Restaurant Reservation',
            openTime: '2 pm - 8 pm',
            isLiked: false,
          },
          {
            id: '2',
            name: 'Walmart 2',
            image: IMAGES.WALMART,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            website: 'www.walmart.com',
            telephone: '(480) 000-0010',
            email: 'walmart@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            category: 'Restaurant Reservation',
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
          },
          {
            id: '3',
            name: 'Walmart 3',
            image: IMAGES.WALMART,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            website: 'www.walmart.com',
            telephone: '(480) 000-0010',
            email: 'walmart@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            category: 'Restaurant Reservation',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
          },
          {
            id: '4',
            name: 'Walmart 4',
            image: IMAGES.WALMART,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            category: 'Restaurant Reservation',
            country: 'UK',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            website: 'www.walmart.com',
            telephone: '(480) 000-0010',
            email: 'walmart@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
          },
          {
            id: '5',
            name: 'Walmart 5',
            image: IMAGES.WALMART,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            website: 'www.walmart.com',
            telephone: '(480) 000-0010',
            email: 'walmart@gmail.com',
            phoneNumber: '1234567890',
            country: 'UK',
            category: 'Restaurant Reservation',
            distance: '4.5 Miles',
            isOpen: true,
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            openTime: '2 pm - 8 pm',
            isLiked: false,
          },
          {
            id: '6',
            name: 'Walmart 6',
            image: IMAGES.WALMART,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            website: 'www.walmart.com',
            telephone: '(480) 000-0010',
            latitude: '37.774929',
            longitude: '-122.419416',
            email: 'walmart@gmail.com',
            phoneNumber: '1234567890',
            category: 'Restaurant Reservation',
            country: 'UK',
            distance: '4.5 Miles',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
          },
        ],
      },
    ],
  },
  {
    id: '3',
    key: 'Groceries',
    subCategories: [],
    items: [
      {
        id: '1',
        name: 'Costco 1',
        image: IMAGES.GROCERY,
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        country: 'UK',
        website: 'www.costco.com',
        telephone: '(480) 000-0010',
        latitude: '37.774929',
        longitude: '-122.419416',
        email: 'costco@gmail.com',
        phoneNumber: '1234567890',
        category: 'Groceries',
        distance: '4.5 Miles',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        isOpen: true,
        openTime: '2 pm - 8 pm',
        isLiked: false,
      },
      {
        id: '2',
        name: 'Walmart 2',
        image: IMAGES.WALMART,
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        country: 'UK',
        website: 'www.walmart.com',
        latitude: '37.774929',
        longitude: '-122.419416',
        telephone: '(480) 000-0010',
        email: 'walmart@gmail.com',
        phoneNumber: '1234567890',
        category: 'Groceries',
        distance: '4.5 Miles',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        isOpen: true,
        openTime: '2 pm - 8 pm',
        isLiked: false,
      },
      {
        id: '3',
        name: 'Costco 3',
        image: IMAGES.GROCERY,
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        country: 'UK',
        website: 'www.costco.com',
        latitude: '37.774929',
        longitude: '-122.419416',
        telephone: '(480) 000-0010',
        email: 'costco@gmail.com',
        phoneNumber: '1234567890',
        distance: '4.5 Miles',
        category: 'Groceries',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        isOpen: true,
        openTime: '2 pm - 8 pm',
        isLiked: false,
      },
      {
        id: '4',
        name: 'Walmart 4',
        image: IMAGES.WALMART,
        website: 'www.walmart.com',
        latitude: '37.774929',
        longitude: '-122.419416',
        telephone: '(480) 000-0010',
        email: 'walmart@gmail.com',
        phoneNumber: '1234567890',
        category: 'Groceries',
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        country: 'UK',
        distance: '4.5 Miles',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        isOpen: true,
        openTime: '2 pm - 8 pm',
        isLiked: false,
      },
      {
        id: '5',
        name: 'Costco 5',
        image: IMAGES.GROCERY,
        website: 'www.costco.com',
        latitude: '37.774929',
        longitude: '-122.419416',
        telephone: '(480) 000-0010',
        email: 'costco@gmail.com',
        phoneNumber: '1234567890',
        category: 'Groceries',
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        country: 'UK',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        distance: '4.5 Miles',
        isOpen: true,
        openTime: '2 pm - 8 pm',
        isLiked: false,
      },
      {
        id: '6',
        name: 'Walmart 6',
        image: IMAGES.WALMART,
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        website: 'www.walmart.com',
        latitude: '37.774929',
        longitude: '-122.419416',
        telephone: '(480) 000-0010',
        email: 'walmart@gmail.com',
        phoneNumber: '1234567890',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        country: 'UK',
        distance: '4.5 Miles',
        isOpen: true,
        openTime: '2 pm - 8 pm',
        isLiked: false,
        category: 'Groceries',
      },
    ],
  },
  {
    id: '4',
    key: 'Wears',
    subCategories: [],
    items: [
      {
        id: '1',
        name: 'Gucci',
        image: IMAGES.GUCCI,
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        category: 'Wears',
        website: 'www.gucci.com',
        latitude: '37.774929',
        longitude: '-122.419416',
        telephone: '(480) 000-0010',
        email: 'gucci@gmail.com',
        phoneNumber: '1234567890',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        country: 'UK',
        distance: '4.5 Miles',
        isOpen: true,
        openTime: '2 pm - 8 pm',
        isLiked: true,
      },
      {
        id: '2',
        name: 'Zara',
        image: IMAGES.ZARA,
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        country: 'UK',
        distance: '4.5 Miles',
        isOpen: true,
        category: 'Wears',
        website: 'www.zara.com',
        latitude: '37.774929',
        longitude: '-122.419416',
        telephone: '(480) 000-0010',
        email: 'zara@gmail.com',
        phoneNumber: '1234567890',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        openTime: '2 pm - 8 pm',
        isLiked: false,
      },
      {
        id: '3',
        name: 'Adidas',
        image: IMAGES.ADIDAS,
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        country: 'UK',
        category: 'Wears',
        website: 'www.adidas.com',
        latitude: '37.774929',
        longitude: '-122.419416',
        telephone: '(480) 000-0010',
        email: 'adidas@gmail.com',
        phoneNumber: '1234567890',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        distance: '4.5 Miles',
        isOpen: true,
        openTime: '2 pm - 8 pm',
        isLiked: false,
      },
      {
        id: '4',
        name: 'Zara',
        image: IMAGES.ZARA,
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        country: 'UK',
        distance: '4.5 Miles',
        category: 'Wears',
        website: 'www.zara.com',
        latitude: '37.774929',
        longitude: '-122.419416',
        telephone: '(480) 000-0010',
        email: 'zara@gmail.com',
        phoneNumber: '1234567890',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        isOpen: true,
        openTime: '2 pm - 8 pm',
        isLiked: false,
      },
      {
        id: '5',
        name: 'Gucci',
        image: IMAGES.GUCCI,
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        country: 'UK',
        category: 'Wears',
        website: 'www.gucci.com',
        latitude: '37.774929',
        longitude: '-122.419416',
        telephone: '(480) 000-0010',
        email: 'gucci@gmail.com',
        phoneNumber: '1234567890',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        distance: '4.5 Miles',
        isOpen: true,
        openTime: '2 pm - 8 pm',
        isLiked: true,
      },
      {
        id: '6',
        name: 'Adidas',
        image: IMAGES.ADIDAS,
        category: 'Wears',
        website: 'www.adidas.com',
        telephone: '(480) 000-0010',
        latitude: '37.774929',
        longitude: '-122.419416',
        email: 'adidas@gmail.com',
        phoneNumber: '1234567890',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        country: 'UK',
        distance: '4.5 Miles',
        isOpen: true,
        openTime: '2 pm - 8 pm',
        isLiked: false,
      },
    ],
  },
  {
    id: '5',
    key: 'Health',
    subCategories: [],
    items: [
      {
        id: '1',
        name: 'Peace Pharmacy 1',
        image: IMAGES.PEACE_PHARMACY,
        address: '123 Maplewood Lane Springfield',
        website: 'www.peacepharmacy.com',
        latitude: '37.774929',
        longitude: '-122.419416',
        telephone: '(480) 000-0010',
        email: 'peacepharmacy@gmail.com',
        phoneNumber: '1234567890',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        city: 'London',
        country: 'UK',
        category: 'Health',
        distance: '4.5 Miles',
        isOpen: true,
        openTime: '2 pm - 8 pm',
        isLiked: false,
      },
      {
        id: '2',
        name: 'Peace Pharmacy 2',
        website: 'www.peacepharmacy.com',
        latitude: '37.774929',
        longitude: '-122.419416',
        telephone: '(480) 000-0010',
        email: 'peacepharmacy@gmail.com',
        phoneNumber: '1234567890',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        image: IMAGES.PEACE_PHARMACY,
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        country: 'UK',
        category: 'Health',
        distance: '4.5 Miles',
        isOpen: true,
        openTime: '2 pm - 8 pm',
        isLiked: true,
      },
      {
        id: '3',
        name: 'Peace Pharmacy 3',
        image: IMAGES.PEACE_PHARMACY,
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        country: 'UK',
        category: 'Health',
        website: 'www.peacepharmacy.com',
        latitude: '37.774929',
        longitude: '-122.419416',
        telephone: '(480) 000-0010',
        email: 'peacepharmacy@gmail.com',
        phoneNumber: '1234567890',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        distance: '4.5 Miles',
        isOpen: true,
        openTime: '2 pm - 8 pm',
        isLiked: false,
      },
      {
        id: '4',
        name: 'Peace Pharmacy 4',
        image: IMAGES.PEACE_PHARMACY,
        address: '123 Maplewood Lane Springfield',
        website: 'www.peacepharmacy.com',
        latitude: '37.774929',
        longitude: '-122.419416',
        telephone: '(480) 000-0010',
        email: 'peacepharmacy@gmail.com',
        phoneNumber: '1234567890',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        city: 'London',
        country: 'UK',
        category: 'Health',
        distance: '4.5 Miles',
        isOpen: true,
        openTime: '2 pm - 8 pm',
        isLiked: false,
      },
      {
        id: '5',
        name: 'Peace Pharmacy 5',
        image: IMAGES.PEACE_PHARMACY,
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        website: 'www.peacepharmacy.com',
        latitude: '37.774929',
        longitude: '-122.419416',
        telephone: '(480) 000-0010',
        email: 'peacepharmacy@gmail.com',
        phoneNumber: '1234567890',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        country: 'UK',
        category: 'Health',
        distance: '4.5 Miles',
        isOpen: true,
        openTime: '2 pm - 8 pm',
        isLiked: true,
      },
      {
        id: '6',
        name: 'Peace Pharmacy 6',
        image: IMAGES.PEACE_PHARMACY,
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        country: 'UK',
        website: 'www.peacepharmacy.com',
        latitude: '37.774929',
        longitude: '-122.419416',
        telephone: '(480) 000-0010',
        email: 'peacepharmacy@gmail.com',
        phoneNumber: '1234567890',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        category: 'Health',
        distance: '4.5 Miles',
        isOpen: true,
        openTime: '2 pm - 8 pm',
        isLiked: true,
      },
    ],
  },
  {
    id: '6',
    key: 'Real State',
    subCategories: [],
    items: [
      {
        id: '1',
        name: 'Property 1',
        image: IMAGES.PROPERTY_1,
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        website: 'www.property1.com',
        latitude: '37.774929',
        longitude: '-122.419416',
        telephone: '(480) 000-0010',
        email: 'property1@gmail.com',
        phoneNumber: '1234567890',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        country: 'UK',
        rating: '4.2',
        isLiked: false,
        category: 'Real State',
      },
      {
        id: '2',
        name: 'Property 2',
        image: IMAGES.PROPERTY_2,
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        website: 'www.property2.com',
        latitude: '37.774929',
        longitude: '-122.419416',
        telephone: '(480) 000-0010',
        email: 'property2@gmail.com',
        phoneNumber: '1234567890',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        country: 'UK',
        rating: '4.2',
        isLiked: false,
        category: 'Real State',
      },
      {
        id: '3',
        name: 'Property 3',
        image: IMAGES.PROPERTY_1,
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        country: 'UK',
        website: 'www.property3.com',
        latitude: '37.774929',
        longitude: '-122.419416',
        telephone: '(480) 000-0010',
        email: 'property3@gmail.com',
        phoneNumber: '1234567890',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        rating: '4.2',
        isLiked: true,
        category: 'Real State',
      },
      {
        id: '4',
        name: 'Property 4',
        image: IMAGES.PROPERTY_2,
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        country: 'UK',
        website: 'www.property4.com',
        latitude: '37.774929',
        longitude: '-122.419416',
        telephone: '(480) 000-0010',
        email: 'property4@gmail.com',
        phoneNumber: '1234567890',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        rating: '4.2',
        isLiked: false,
        category: 'Real State',
      },
      {
        id: '5',
        name: 'Property 5',
        image: IMAGES.PROPERTY_1,
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        country: 'UK',
        rating: '4.2',
        website: 'www.property5.com',
        latitude: '37.774929',
        longitude: '-122.419416',
        telephone: '(480) 000-0010',
        email: 'property5@gmail.com',
        phoneNumber: '1234567890',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        isLiked: true,
        category: 'Real State',
      },
      {
        id: '6',
        name: 'Property 6',
        image: IMAGES.PROPERTY_2,
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        website: 'www.property6.com',
        latitude: '37.774929',
        longitude: '-122.419416',
        telephone: '(480) 000-0010',
        email: 'property6@gmail.com',
        phoneNumber: '1234567890',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        country: 'UK',
        rating: '4.2',
        isLiked: false,
        category: 'Real State',
      },
    ],
  },
  {
    id: '7',
    key: 'Events',
    subCategories: [],
    items: [
      {
        id: '1',
        name: 'Event 1',
        image: IMAGES.EVENT_1,
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        country: 'UK',
        distance: '4.5 Miles',
        latitude: '37.774929',
        longitude: '-122.419416',
        isOpen: true,
        website: 'www.event1.com',
        telephone: '(480) 000-0010',
        email: 'event1@gmail.com',
        phoneNumber: '1234567890',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        openTime: '2 pm - 8 pm',
        rating: '4.2',
        isLiked: true,
        category: 'Events',
      },
      {
        id: '2',
        name: 'Event 2',
        image: IMAGES.EVENT_2,
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        country: 'UK',
        distance: '4.5 Miles',
        latitude: '37.774929',
        longitude: '-122.419416',
        isOpen: true,
        openTime: '2 pm - 8 pm',
        rating: '4.2',
        website: 'www.event2.com',
        telephone: '(480) 000-0010',
        email: 'event2@gmail.com',
        phoneNumber: '1234567890',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        isLiked: false,
        category: 'Events',
      },
      {
        id: '3',
        name: 'Event 3',
        image: IMAGES.EVENT_1,
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        country: 'UK',
        distance: '4.5 Miles',
        website: 'www.event3.com',
        telephone: '(480) 000-0010',
        email: 'event3@gmail.com',
        phoneNumber: '1234567890',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        latitude: '37.774929',
        longitude: '-122.419416',
        isOpen: true,
        openTime: '2 pm - 8 pm',
        rating: '4.2',
        isLiked: false,
        category: 'Events',
      },
      {
        id: '4',
        name: 'Event 4',
        image: IMAGES.EVENT_2,
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        country: 'UK',
        distance: '4.5 Miles',
        website: 'www.event4.com',
        telephone: '(480) 000-0010',
        email: 'event4@gmail.com',
        phoneNumber: '1234567890',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        latitude: '37.774929',
        longitude: '-122.419416',
        isOpen: true,
        openTime: '2 pm - 8 pm',
        rating: '4.2',
        isLiked: true,
        category: 'Events',
      },
      {
        id: '5',
        name: 'Event 5',
        image: IMAGES.EVENT_1,
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        country: 'UK',
        website: 'www.event5.com',
        telephone: '(480) 000-0010',

        phoneNumber: '1234567890',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        distance: '4.5 Miles',
        latitude: '37.774929',
        longitude: '-122.419416',
        isOpen: true,
        openTime: '2 pm - 8 pm',
        rating: '4.2',
        isLiked: false,
        category: 'Events',
      },
      {
        id: '6',
        name: 'Event 6',
        image: IMAGES.EVENT_2,
        address: '123 Maplewood Lane Springfield',
        city: 'London',
        country: 'UK',
        distance: '4.5 Miles',
        category: 'Events',
        latitude: '37.774929',
        longitude: '-122.419416',
        isOpen: true,
        openTime: '2 pm - 8 pm',
        rating: '4.2',
        website: 'www.event6.com',
        telephone: '(480) 000-0010',
        email: 'event6@gmail.com',
        phoneNumber: '1234567890',
        description: TEMPORARY_TEXT.LORUM_IPSUM,
        isLiked: true,
      },
    ],
  },
  {
    id: '8',
    key: 'Others',
    subCategories: [
      {
        id: '1',
        key: 'Electronics',
        image: IMAGES.ELECTRONICS,
        items: [
          {
            id: '1',
            name: 'Appliance Electronics UK Ltd',
            image: IMAGES.ELECTRONICS_1,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            website: 'www.applianceelectronics.com',
            telephone: '(480) 000-0010',
            email: 'applianceelectronics@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            isOpen: true,
            category: 'Electronics',
            openTime: '2 pm - 8 pm',
            isLiked: false,
          },
          {
            id: '2',
            name: 'Appliance Electronics UK Ltd',
            image: IMAGES.ELECTRONICS_2,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            website: 'www.applianceelectronics.com',
            telephone: '(480) 000-0010',
            email: 'applianceelectronics@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            category: 'Electronics',
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
          },
          {
            id: '3',
            name: 'Appliance Electronics UK Ltd',
            image: IMAGES.ELECTRONICS_1,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            website: 'www.applianceelectronics.com',
            telephone: '(480) 000-0010',
            email: 'applianceelectronics@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            category: 'Electronics',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
          },
          {
            id: '4',
            name: 'Appliance Electronics UK Ltd',
            image: IMAGES.ELECTRONICS_2,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            category: 'Electronics',
            country: 'UK',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            website: 'www.applianceelectronics.com',
            telephone: '(480) 000-0010',
            email: 'applianceelectronics@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
          },
          {
            id: '5',
            name: 'Appliance Electronics UK Ltd',
            image: IMAGES.ELECTRONICS_1,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            website: 'www.applianceelectronics.com',
            telephone: '(480) 000-0010',
            email: 'applianceelectronics@gmail.com',
            phoneNumber: '1234567890',
            country: 'UK',
            category: 'Electronics',
            distance: '4.5 Miles',
            isOpen: true,
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            openTime: '2 pm - 8 pm',
            isLiked: false,
          },
          {
            id: '6',
            name: 'Appliance Electronics UK Ltd',
            image: IMAGES.ELECTRONICS_2,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            website: 'www.walmart.com',
            telephone: '(480) 000-0010',
            latitude: '37.774929',
            longitude: '-122.419416',
            email: 'walmart@gmail.com',
            phoneNumber: '1234567890',
            category: 'Electronics',
            country: 'UK',
            distance: '4.5 Miles',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
          },
        ],
      },
      {
        id: '2',
        key: 'Interior',
        image: IMAGES.INTERIOR,
        items: [
          {
            id: '1',
            name: 'High Class Touch',
            image: IMAGES.INTERIOR_1,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            website: 'www.highclasstouch.com',
            telephone: '(480) 000-0010',
            email: 'highclasstouch@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            isOpen: true,
            category: 'Interior',
            openTime: '2 pm - 8 pm',
            isLiked: false,
          },
          {
            id: '2',
            name: 'High Class Touch',
            image: IMAGES.INTERIOR_2,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            website: 'www.highclasstouch.com',
            telephone: '(480) 000-0010',
            email: 'highclasstouch@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            category: 'Interior',
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
          },
          {
            id: '3',
            name: 'High Class Touch',
            image: IMAGES.INTERIOR_1,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            country: 'UK',
            website: 'www.highclasstouch.com',
            telephone: '(480) 000-0010',
            email: 'highclasstouch@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            category: 'Interior',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
          },
          {
            id: '4',
            name: 'High Class Touch',
            image: IMAGES.INTERIOR_2,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            category: 'Interior',
            country: 'UK',
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            website: 'www.highclasstouch.com',
            telephone: '(480) 000-0010',
            email: 'highclasstouch@gmail.com',
            phoneNumber: '1234567890',
            distance: '4.5 Miles',
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
          },
          {
            id: '5',
            name: 'High Class Touch',
            image: IMAGES.INTERIOR_1,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            website: 'www.highclasstouch.com',
            telephone: '(480) 000-0010',
            email: 'highclasstouch@gmail.com',
            phoneNumber: '1234567890',
            country: 'UK',
            category: 'Interior',
            distance: '4.5 Miles',
            isOpen: true,
            latitude: '37.774929',
            longitude: '-122.419416',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            openTime: '2 pm - 8 pm',
            isLiked: false,
          },
          {
            id: '6',
            name: 'High Class Touch',
            image: IMAGES.INTERIOR_2,
            address: '123 Maplewood Lane Springfield',
            city: 'London',
            website: 'www.highclasstouch.com',
            telephone: '(480) 000-0010',
            email: 'highclasstouch@gmail.com',
            latitude: '37.774929',
            longitude: '-122.419416',
            phoneNumber: '1234567890',
            category: 'Interior',
            country: 'UK',
            distance: '4.5 Miles',
            description: TEMPORARY_TEXT.LORUM_IPSUM,
            isOpen: true,
            openTime: '2 pm - 8 pm',
            isLiked: false,
          },
        ],
      },
    ],
  },
];

const renderSeeAll = ({
  heading,
  items,
  itemHeading,
}: {
  heading: string;
  items: ItemType[];
  itemHeading: string;
}) => {
  return (
    <RowComponent style={{ marginBottom: 15, ...STYLES.CONTAINER }}>
      <Typography numberOfLines={1} style={{ fontWeight: FontWeight.SemiBold, width: '80%' }}>
        {heading}
      </Typography>
      <Typography
        onPress={() => {
          navigate(SCREENS.VIEW_ALL, { data: { items, headerTitle: itemHeading } });
        }}
        style={{
          color: COLORS.BORDER,
          fontSize: FontSize.Small,
          fontWeight: FontWeight.SemiBold,
        }}
      >
        {COMMON_TEXT.VIEW_ALL}
      </Typography>
    </RowComponent>
  );
};

export const renderItems = ({ item }: { item: ItemType }) => (
  <ItemCard item={item} key={item?.id} />
);
export const renderFoodItems = ({ item }: { item: ItemType }) => (
  <FoodCard item={item} key={item?.id} />
);

export const renderHorizontalItemsWithRow = ({
  data,
  heading,
  rowHeading,
}: {
  data: ItemType[];
  heading: string;
  rowHeading: string;
}) => {
  return (
    <>
      {renderSeeAll({
        heading: rowHeading,
        items: data ?? [],
        itemHeading: heading,
      })}
      <FlatListComponent
        horizontal={true}
        keyExtractor={item => item?.id}
        contentContainerStyle={styles.subCategoriesContentContainer}
        data={data?.slice(0, 3) ?? []}
        renderItem={renderItems}
      />
    </>
  );
};
export const renderHorizontalFoodItemsWithRow = ({
  data,
  heading,
  rowHeading,
}: {
  data: ItemType[];
  heading: string;
  rowHeading: string;
}) => {
  return (
    <>
      {renderSeeAll({
        heading: rowHeading,
        items: data ?? [],
        itemHeading: heading,
      })}
      <FlatListComponent
        horizontal={true}
        keyExtractor={item => item?.id}
        contentContainerStyle={styles.subCategoriesContentContainer}
        data={data?.slice(0, 5) ?? []}
        renderItem={renderFoodItems}
      />
    </>
  );
};
